account_id = "639bf478ca1dd22f9c087ec5003b42b9"
name = "jacob-software-dev"
type = "webpack"
workers_dev = true

[env.staging]
name = "jacob-software-staging"
route = "staging.jacob.software/*"
zone_id = "ca5de4ef1b5ee3ee7e7db73fb04b6bd0"
workers_dev = false

[env.production]
name = "jacob-software"
route = "jacob.software/*"
zone_id = "ca5de4ef1b5ee3ee7e7db73fb04b6bd0"
workers_dev = false

[site]
bucket = "./public"
entry-point = "workers-site"
