name: Test
on:
  push:
    branches-ignore:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Caching node modules
      id: modules-cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
    - name: Caching node modules
      id: stylelint-cache
      uses: actions/cache@v1
      with:
        path: ./stylelintcache
        key: ${{ runner.os }}-stylelint-${{ hashFiles('src/**/*.scss') }}
    - run: yarn install
      if: steps.modules-cache.outputs.cache-hit == false
    - run: yarn lint:js
    - run: yarn lint:css
