name: Deploy Staging
on:
  push:
    branches:
      - develop
env:
  NODE_ENV: production
  YARN_PRODUCTION: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Caching node modules
      id: modules-cache-staging
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-prod-${{ hashFiles('yarn.lock') }}
    - run: yarn install
      if: steps.modules-cache-staging.outputs.cache-hit == false
    - run: yarn build
    - name: Publish
      uses: cloudflare/wrangler-action@1.0.0
      with:
        apiKey: ${{ secrets.CF_API_KEY }}
        email: ${{ secrets.CF_EMAIL }}
        environment: 'staging'
